{
  "_args": [
    [
      "react-transform-catch-errors@1.0.2",
      "/home/brittny/demo-blacklight/app/javascript/browserify"
    ]
  ],
  "_development": true,
  "_from": "react-transform-catch-errors@1.0.2",
  "_id": "react-transform-catch-errors@1.0.2",
  "_inBundle": false,
  "_integrity": "sha512-FCeTXLTpRM8wMrwAlYVoEI+HXUFYEJLKdmf9zd5YtH1yc2Dq81JL1YMr0eHeUe699CCTezG4CfEB5D9RpmovEw==",
  "_location": "/react-transform-catch-errors",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "react-transform-catch-errors@1.0.2",
    "name": "react-transform-catch-errors",
    "escapedName": "react-transform-catch-errors",
    "rawSpec": "1.0.2",
    "saveSpec": null,
    "fetchSpec": "1.0.2"
  },
  "_requiredBy": [
    "/nwb"
  ],
  "_resolved": "https://registry.npmjs.org/react-transform-catch-errors/-/react-transform-catch-errors-1.0.2.tgz",
  "_spec": "1.0.2",
  "_where": "/home/brittny/demo-blacklight/app/javascript/browserify",
  "author": {
    "name": "Dan Abramov",
    "email": "dan.abramov@me.com"
  },
  "bugs": {
    "url": "https://github.com/gaearon/react-transform-catch-errors/issues"
  },
  "description": "React Transform that catches errors inside React components",
  "devDependencies": {
    "babel-cli": "^6.3.17",
    "babel-core": "^6.3.21",
    "babel-preset-es2015": "^6.3.3",
    "babel-preset-stage-0": "^6.3.13",
    "rimraf": "^2.4.3"
  },
  "files": [
    "lib",
    "src"
  ],
  "homepage": "https://github.com/gaearon/react-transform-catch-errors#readme",
  "keywords": [
    "react-transform",
    "react",
    "reactjs",
    "errors",
    "rhl",
    "dx"
  ],
  "license": "MIT",
  "main": "lib/index.js",
  "name": "react-transform-catch-errors",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gaearon/react-transform-catch-errors.git"
  },
  "scripts": {
    "build": "babel src --out-dir lib",
    "clean": "rimraf lib",
    "prepublish": "npm run clean && npm run build"
  },
  "version": "1.0.2"
}
